/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package challenge.view;

import challenge.controller.QuitoPicoYPlacaController;
import challenge.models.User;

/**
 *
 * @author diego
 */
public class PicoYPlacaForm extends javax.swing.JFrame implements PicoYPlacaView{

    private User userInfo;
    
    /**
     * Creates new form PicoYPlacaForm
     * @param userInfo
     */
    public PicoYPlacaForm(User userInfo) {
        initComponents();
       this.userInfo = userInfo;
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsult = new javax.swing.JButton();
        txtFieldPlateNumber = new javax.swing.JTextField();
        txtFieldDate = new javax.swing.JTextField();
        lblPlateNumber = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        txtFieldHour = new javax.swing.JTextField();
        lblHour = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConsult.setText("Consultar");

        lblPlateNumber.setText("Número de Placa");

        lblDate.setText("Fecha");

        lblHour.setText("Hora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlateNumber)
                            .addComponent(lblDate)
                            .addComponent(lblHour))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFieldDate, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtFieldPlateNumber)
                            .addComponent(txtFieldHour))
                        .addGap(46, 46, 46)
                        .addComponent(btnConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConsult, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldPlateNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPlateNumber))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHour))))
                .addGap(63, 63, 63)
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsult;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblPlateNumber;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtFieldDate;
    private javax.swing.JTextField txtFieldHour;
    private javax.swing.JTextField txtFieldPlateNumber;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addController(QuitoPicoYPlacaController controller){
        btnConsult.addActionListener(controller);

        
    }
    
    @Override
    public User getUserInfo() {
       this.userInfo = new User(txtFieldPlateNumber.getText(), txtFieldDate.getText(), txtFieldHour.getText());
       return this.userInfo;
    }

    @Override
    public void showPlateError(String message) {
        lblResult.setText(message);
    }

    @Override
    public void showOnRoadMessage(String message) {
        lblResult.setText(message);
    }

    @Override
    public void showDateFormatError(String message) {
        lblResult.setText(message);
    }
    
    @Override
    public void showEmptyValueError(String message) {
        lblResult.setText(message);
    }

}
